### ISSUE TITLE
Korb can't see my PVC, getting the wrong namespace

### ISSUE THREAD

**Issue by phybros** [BeryJu/korb#54]
Got a PVC "home-home-assistant" in the namespace `home` and trying to copy it to a different StorageClass (same namespace).

I used this command:

```
$ korb --kubeConfig=./kubeconfig --new-pvc-name home-assistant-config-v1 --new-pvc-storage-class rook-ceph-block home-home-assistant
DEBU[0000] Created client from kubeconfig                component=migrator kubeconfig=./kubeconfig
DEBU[0000] Got current namespace                         component=migrator namespace=default
PANI[0000] Failed to get Source PVC                      component=migrator error="persistentvolumeclaims \"home-home-assistant\" not found"
panic: (*logrus.Entry) 0xc0003ff8f0

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc0003ff880, 0x0, 0xc00049e048, 0x18)
	github.com/sirupsen/logrus@v1.8.1/entry.go:259 +0x2e5
github.com/sirupsen/logrus.(*Entry).Log(0xc0003ff880, 0xc000000000, 0xc0001af080, 0x1, 0x1)
	github.com/sirupsen/logrus@v1.8.1/entry.go:293 +0x86
github.com/sirupsen/logrus.(*Entry).Panic(...)
	github.com/sirupsen/logrus@v1.8.1/entry.go:331
github.com/BeryJu/korb/pkg/migrator.(*Migrator).validateSourcePVC(0xc0003e7f10, 0x8)
	github.com/BeryJu/korb/pkg/migrator/validate.go:31 +0x26e
github.com/BeryJu/korb/pkg/migrator.(*Migrator).Validate(0xc0003e7f10, 0x0, 0x0, 0x0, 0x0)
	github.com/BeryJu/korb/pkg/migrator/validate.go:12 +0x45
github.com/BeryJu/korb/pkg/migrator.(*Migrator).Run(0xc0003e7f10)
	github.com/BeryJu/korb/pkg/migrator/migrator.go:65 +0x45
github.com/BeryJu/korb/cmd.glob..func1(0x2f2b580, 0xc0003c59e0, 0x1, 0x6)
	github.com/BeryJu/korb/cmd/root.go:41 +0x125
github.com/spf13/cobra.(*Command).execute(0x2f2b580, 0xc00003a080, 0x6, 0x6, 0x2f2b580, 0xc00003a080)
	github.com/spf13/cobra@v1.2.1/command.go:860 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x2f2b580, 0x2f3d140, 0x0, 0xc00005e778)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
github.com/BeryJu/korb/cmd.Execute()
	github.com/BeryJu/korb/cmd/root.go:52 +0x31
main.main()
	github.com/BeryJu/korb/main.go:6 +0x25
```

But as you can see it does exist:

```
$ k get pvc -n home
NAME                  STATUS   VOLUME                CAPACITY   ACCESS MODES   STORAGECLASS      AGE
home-home-assistant   Bound    home-home-assistant   1Gi        RWO            longhorn-static   22m
```

**Comment by phybros** [comment]
OK. I worked around this by doing `kubectl config set-context --current --namespace=home` and then it worked!

Is there any way to be able to specify `--old-pvc-namespace` and `--new-pvc-namespace`? That would be amazing, because then you could also move PVCs between namespaces without changing storageclass/size/name.

e.g. `korb --old-pvc-namespace default --new-pvc-namespace home my-pvc-name`. It would be amazing!

**Comment by BeryJu** [comment]
So I just added that here https://github.com/BeryJu/korb/commit/7fc621777bb3a9861e20ba806bbc47abb443d766 only to realise that it won't work 🙃

The way korb currently copies data is to just mount both volumes in a pod and rsync them. However, you can't mount PVCs from another namespace, so that won't unless I re-work it to send data via the network.

**Comment by phybros** [comment]
That's fair. I think still haveing the source PVC NS be a config option would be awesome instead of it using the default context ns. That would still be a big win!
